### ISSUE TITLE
Error: Got empty quote response from the connector

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp#62]
In UI, Sending from Blue Demo to Red Demo fails to get quote, but Red to Blue is okay for some reason). 

At testing with sample code for sending...

```
request: { address: 'ilpdemo.blue.winthan.6d58cadf-816d-4d42-9337-1ad52e49085c',
  amount: '10',
  expires_at: '2016-12-16T10:37:46.961Z',
  condition: 'cc:0:3:8UbkYVu_IquZ6Skp9VjKabB6d_iE5ayeRFdB1KS4zPE:32' }
Error: Got empty quote response from the connector
    at client.connect.then.then.then (/Users/winthan/node/node_modules/ilp/src/lib/sender.js:115:17)
```

From sgd.interledger to usd.interledger  ( Both connectors are having the peer public keys in connector ledgers for trust, and it broadcasts all time.  But it is having as following quote issues.

```
request: { address: 'sg.sgd.interledger.winthan.3f2ccf06-f8ed-437f-b17e-e430431a92bc',
  amount: '10',
  expires_at: '2016-12-16T10:39:12.615Z',
  condition: 'cc:0:3:xz5KorW4n3f2F4eCSJZxJZXBTqiZnRtCc8nwqXvwUK0:32' }
Error: Got empty quote response from the connector
    at client.connect.then.then.then (/Users/winthan/node/node_modules/ilp/src/lib/sender.js:115:17)
```

**Comment by sharafian** [comment]
Could you share a log file? (either the entire one, or the few seconds surrounding this error)

**Comment by Winthan** [comment]
That one is the entire log when I use for sender and receiver code. 

```
'use strict'

const co = require('co')
const ILP = require('ilp')
const FiveBellsLedgerPlugin = require('ilp-plugin-bells')

const  sender  = ILP.createSender({
  _plugin: FiveBellsLedgerPlugin,
  prefix: 'ilpdemo.red.',
  account: 'https://red.ilpdemo.org/ledger/accounts/alice',
  password: 'alice'
})

const receiver  = ILP.createReceiver({
  _plugin: FiveBellsLedgerPlugin,
  prefix: 'ilpdemo.blue.',
  account: 'https://blue.ilpdemo.org/ledger/accounts/winthan',
  password: 'whatever'
})

co(function * () {
  yield receiver.listen()
  receiver.on('incoming', (transfer, fulfillment) => {
    console.log('received transfer:', transfer)
    console.log('fulfilled transfer hold with fulfillment:', fulfillment)
  })

  const request = receiver.createRequest({
    amount: '10',
  })
  console.log('request:', request)

  const paymentParams = yield sender.quoteRequest(request)
  console.log('paymentParams', paymentParams)

  const result = yield sender.payRequest(paymentParams)
  console.log('sender result:', result)
}).catch((err) => {
  console.log(err)
})



```

ILP Kit has same error for getting quotes.  Following is logs from ILP Kit. destinationAddress doesn't have Condition in ILP kit log. 

```
[ledger] 2016-12-16T11:23:47.322Z ledger:koa info --> GET /accounts/testing 200 22ms 198B
[ledger] 2016-12-16T11:23:49.480Z ledger:koa info <-- POST /messages
[ledger] 2016-12-16T11:23:49.495Z ledger:koa info --> POST /messages 201 15ms 384B
[connector] 2016-12-16T11:23:49.498Z connector:route-builder info creating quote sourceAddress=us.usd.interledger.testing sourceAmount=10 destinationAddress=sg.sgd.interledger.winthan destinationAmount=undefined destinationPrecisionAndScale=undefined slippage=undefined
[ledger] 2016-12-16T11:23:49.669Z ledger:koa info <-- POST /messages
[ledger] 2016-12-16T11:23:49.684Z ledger:koa info --> POST /messages 201 14ms 351B
 [api] Error: Got empty quote response from the connector
[api]     at client.connect.then.then.then (/home/winthan/ilp-kit/node_modules/ilp/src/lib/sender.js:55:17)
 [api] 2016-12-16T11:23:49.696Z error-handler WARN Not Found: No quote for a specified destination/amount has been found
 [api] 2016-12-16T11:23:49.699Z http INFO   --> POST /payments/quote 404 2,408ms -
[connector] 2016-12-16T11:23:53.117Z connector:route-broadcaster info broadcasting 1 routes to peer.ZA7pw.sgd.aH3UoxkGPbupi32RJIZnl70wzQhfclUtWFWIsB7pVks

```

**Comment by Winthan** [comment]
@sharafian  - I think I have fixed with this [#139](https://github.com/interledgerjs/ilp-kit/issues/139) by entering exact Peer name in ENV.list for getting the quote from ledger A and B. But for some reasons, I don't get any status of receiving when payment made. 

Please see at this [#140](https://github.com/interledgerjs/ilp-kit/issues/140) for database entry for payment to show in history at UI if we make payment without ILP Kit UI.

**Comment by sharafian** [comment]
From your logs it looks like you aren't getting route broadcasts from your peer, and so you don't have a route to the destination. Could you check your logs and make sure you're receiving route broadcasts? If you have `DEBUG=ilp*` set (in the environment, but not `env.list`), you should see something like:

```
[connector] 1 got request with id 6335b81c-3464-4bb3-89d8-ade06c915921 for method sendMessage with params [ { ledger: 'peer.YPRsW.eur.',
[connector]     account: 'peer.YPRsW.eur.MWdMbwzrgnShgDSke7-4Fqe_NVdzItsOYRkLkzq2zHI',
[connector]     data: { method: 'broadcast_routes', data: [Object] } } ]
[connector] 1 sending reponse { result: true,
[connector]   error: null,
[connector]   id: '6335b81c-3464-4bb3-89d8-ade06c915921' }
```

**Comment by Winthan** [comment]
@sharafian - I am getting quotes, thus I think the route is broadcasting. But I cannot send for some reasons. 

This is the first error I get when I start the app.

---- 
```
[connector] 2016-12-20T13:06:15.100Z connector:route-broadcaster info broadcasting 0 routes to peer.2lF5l.mmk.hDjrJJBkOb8Jf9QRYBVInB4f20nhdYGFsEYh4Z1fCio
[connector] 2016-12-20T13:06:15.101Z connector:app error TypeError: Cannot read property 'sendMessage' of null
[connector]     at RouteBroadcaster._broadcastToLedger (/home/winthan/usd/node_modules/ilp-connector/src/lib/route-broadcaster.js:86:67)
[connector]     at RouteBroadcaster.broadcast (/home/winthan/usd/node_modules/ilp-connector/src/lib/route-broadcaster.js:72:12)
[connector]     at RouteBroadcaster.start (/home/winthan/usd/node_modules/ilp-connector/src/lib/route-broadcaster.js:50:12)
[connector]     at next (native)
[connector]     at onFulfilled (/home/winthan/usd/node_modules/co/index.js:65:19)
[connector]     at process._tickCallback (internal/process/next_tick.js:103:7)
[connector] undefined: connected! subscribing to channel `undefined/B-G4DuW9B3NQk9bPYvLGy57zj-e0CbTAqBHJJtUaKis`
```
-----

This is what I get I send payment

--------------------- 
```
[ledger] 2016-12-20T13:08:46.630Z ledger:koa info <-- GET /accounts/admin
[ledger] 2016-12-20T13:08:46.656Z ledger:koa info --> GET /accounts/admin 200 26ms 219B
[api] webfinger account
[api]   ilp-kit:spsp created a sender object +20s
[api]   ilp-core remote quote connector=us.usd.usd.usd query={"source_address":"us.usd.usd.admin","destination_address":"mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25","destination_amount":"1369.99"} +1s
[ledger] 2016-12-20T13:08:49.962Z ledger:koa info <-- POST /messages
[ledger] 2016-12-20T13:08:49.977Z ledger:koa info --> POST /messages 201 15ms 407B
[connector] notify message https://usd.interledger.network/ledger/accounts/admin
[connector] 2016-12-20T13:08:49.981Z connector:route-builder info creating quote sourceAddress=us.usd.usd.admin sourceAmount=undefined destinationAddress=mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25 destinationAmount=1369.99 destinationPrecisionAndScale=undefined slippage=undefined
[connector]   ilp-routing:routing-tables searching best hop from us.usd.usd.admin to mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25 for 1369.99 (by dst amount) +36s
[ledger] 2016-12-20T13:08:49.994Z ledger:koa info <-- POST /messages
[ledger] 2016-12-20T13:08:50.017Z ledger:koa info --> POST /messages 201 23ms 491B
[api]   ilp-plugin-bells:factory sending notification to https://usd.interledger.network/ledger/accounts/admin +96ms
[api]   ilp-plugin-bells:plugin notify message https://usd.interledger.network/ledger/accounts/usd +1ms
[api]   ilp:sender got quote response { sourceAmount: '1.01',
[api]   destinationAmount: '1369.990000',
[api]   connectorAccount: 'us.usd.usd.usd',
[api]   sourceExpiryDuration: '6' } +1ms
[api]   ilp:sender sending payment: { sourceAmount: '1.01',
[api]   connectorAccount: 'us.usd.usd.usd',
[api]   destinationAmount: '1369.99',
[api]   destinationAccount: 'mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25',
[api]   destinationMemo: { data: undefined, expires_at: '2016-12-20T13:09:19.800Z' },
[api]   expiresAt: '2016-12-20T13:09:00.033Z',
[api]   executionCondition: 'cc:0:3:rvmcZFFMbU2BncSEgQMMpBhtkg9eHTNoyJNFexKrfPo:32',
[api]   uuid: '16598589-056a-4736-850c-a7d91412bad9' } +12ms
[api]   ilp-plugin-bells:plugin submitting transfer:  {"id":"https://usd.interledger.network/ledger/transfers/16598589-056a-4736-850c-a7d91412bad9","ledger":"https://usd.interledger.network/ledger","debits":[{"account":"https://usd.interledger.network/ledger/accounts/admin","amount":"1.01","authorized":true}],"credits":[{"account":"https://usd.interledger.network/ledger/accounts/usd","amount":"1.01","memo":{"ilp_header":{"account":"mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25","amount":"1369.99","data":{"expires_at":"2016-12-20T13:09:19.800Z"}}}}],"execution_condition":"cc:0:3:rvmcZFFMbU2BncSEgQMMpBhtkg9eHTNoyJNFexKrfPo:32","expires_at":"2016-12-20T13:09:00.033Z"} +3ms
[ledger] 2016-12-20T13:08:50.068Z ledger:koa info <-- PUT /transfers/16598589-056a-4736-850c-a7d91412bad9
[api]   ilp:sender payment sent { sourceAmount: '1.01',
[api]   connectorAccount: 'us.usd.usd.usd',
[api]   destinationAmount: '1369.99',
[api]   destinationAccount: 'mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25',
[api]   destinationMemo: { data: undefined, expires_at: '2016-12-20T13:09:19.800Z' },
[api]   expiresAt: '2016-12-20T13:09:00.033Z',
[api]   executionCondition: 'cc:0:3:rvmcZFFMbU2BncSEgQMMpBhtkg9eHTNoyJNFexKrfPo:32',
[api]   uuid: '16598589-056a-4736-850c-a7d91412bad9' } +198ms
[ledger] 2016-12-20T13:08:50.242Z ledger:koa info --> PUT /transfers/16598589-056a-4736-850c-a7d91412bad9 201 175ms 743B
[connector] notify transfer prepared https://usd.interledger.network/ledger/transfers/16598589-056a-4736-850c-a7d91412bad9
[api]   ilp-plugin-bells:factory sending notification to https://usd.interledger.network/ledger/accounts/admin +12ms
[api]   ilp-plugin-bells:plugin notify transfer prepared https://usd.interledger.network/ledger/transfers/16598589-056a-4736-850c-a7d91412bad9 +1ms
[connector] 2016-12-20T13:08:50.266Z connector:route-builder info constructing destination transfer sourceLedger=us.usd.usd. sourceAmount=1.01 ilpHeader={"account":"mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25","amount":"1369.99","data":{"expires_at":"2016-12-20T13:09:19.800Z"}}
[connector]   ilp-routing:routing-tables searching best hop from us.usd.usd. to mm.mmk.mmk.winthan.17971cdd-301c-482e-a2b3-bc7466388e25 for 1.01 (by src amount) +286ms
[connector] stored 3045667c-9e52-4a87-8aab-172ae8ec5fc5 isIncoming false
[connector] 1 calling sendTransfer with [ { id: '3045667c-9e52-4a87-8aab-172ae8ec5fc5',
[connector]     ledger: 'peer.2lF5l.mmk.',
[connector]     direction: 'outgoing',
[connector]     account: 'peer.2lF5l.mmk.B-G4DuW9B3NQk9bPYvLGy57zj-e0CbTAqBHJJtUaKis',
[connector]     amount: '1369.99',
[connector]     data: { ilp_header: [Object] },
[connector]     noteToSelf: undefined,
[connector]     executionCondition: 'cc:0:3:rvmcZFFMbU2BncSEgQMMpBhtkg9eHTNoyJNFexKrfPo:32',
[connector]     expiresAt: '2016-12-20T13:08:59.033Z' } ] and id c468b992-41ef-44fd-9b2e-1d92e0d59d81
[connector] 1 got response on id c468b992-41ef-44fd-9b2e-1d92e0d59d81
[connector] AssetsNotTradedError during transfer 3045667c-9e52-4a87-8aab-172ae8ec5fc5
[ledger] 2016-12-20T13:08:50.798Z ledger:koa info <-- PUT /transfers/16598589-056a-4736-850c-a7d91412bad9/rejection
[connector] 2016-12-20T13:08:50.980Z connector:subscriptions warn error processing notification: AssetsNotTradedError: This connector does not support the given asset pair
[connector] AssetsNotTradedError: This connector does not support the given asset pair
[connector]     at JsonRpc1.once (/home/winthan/usd/node_modules/ilp-plugin-virtual/src/model/rpc.js:77:19)
[connector]     at JsonRpc1.g (events.js:291:16)
[connector]     at emitOne (events.js:96:13)
[connector]     at JsonRpc1.emit (events.js:188:7)
[connector]     at JsonRpc1._handleResponse (/home/winthan/usd/node_modules/ilp-plugin-virtual/src/model/rpc.js:67:12)
[connector]     at next (native)
[connector]     at onFulfilled (/home/winthan/usd/node_modules/co/index.js:65:19)
[connector]     at /home/winthan/usd/node_modules/co/index.js:54:5
[connector]     at JsonRpc1.co (/home/winthan/usd/node_modules/co/index.js:50:10)
[connector]     at JsonRpc1.createPromise (/home/winthan/usd/node_modules/co/index.js:30:15)
[connector]     at Connection.JsonRpc1._connection.on (/home/winthan/usd/node_modules/ilp-plugin-virtual/src/model/rpc.js:22:39)
[connector]     at emitOne (events.js:96:13)
[connector]     at Connection.emit (events.js:188:7)
[connector]     at MqttClient.client.on.err (/home/winthan/usd/node_modules/ilp-plugin-virtual/src/model/connection.js:44:14)
[connector]     at emitThree (events.js:116:13)
[connector]     at MqttClient.emit (events.js:194:7)
[ledger] 2016-12-20T13:08:50.986Z ledger:koa info --> PUT /transfers/16598589-056a-4736-850c-a7d91412bad9/rejection 201 188ms 81B
[api]   ilp-plugin-bells:factory sending notification to https://usd.interledger.network/ledger/accounts/admin +737ms
[api]   ilp-plugin-bells:plugin notify transfer rejected https://usd.interledger.network/ledger/transfers/16598589-056a-4736-850c-a7d91412bad9 +0ms
[connector] notify transfer rejected https://usd.interledger.network/ledger/transfers/16598589-056a-4736-850c-a7d91412bad9
[api]   ilp:sender transfer timed out +9s
[api] 2016-12-20T13:09:00.039Z error-handler ERROR { Error: Transfer expired, money returned
[api]     at Timeout.setTimeout (/home/winthan/usd/node_modules/ilp/src/lib/sender.js:177:20)
[api]     at ontimeout (timers.js:365:14)
[api]     at tryOnTimeout (timers.js:237:5)
[api]     at Timer.listOnTimeout (timers.js:207:5) headers: { 'Access-Control-Allow-Origin': '*' } }
[api] 2016-12-20T13:09:00.046Z error-handler ERROR Error: Transfer expired, money returned
[api]     at Timeout.setTimeout (/home/winthan/usd/node_modules/ilp/src/lib/sender.js:177:20)
[api]     at ontimeout (timers.js:365:14)
[api]     at tryOnTimeout (timers.js:237:5)
[api]     at Timer.listOnTimeout (timers.js:207:5)
[api] 2016-12-20T13:09:00.052Z http INFO   xxx PUT /payments/33a62f46-6ef2-43df-b0b4-a52ce07789be 500 13s -
[api] 
[api]   InternalServerError: Error: Transfer expired, money returned
[api]       at Object.throw (/home/winthan/usd/node_modules/koa.io/node_modules/koa/lib/context.js:90:23)
[api]       at Object.handleError (/home/winthan/usd/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
[api]       at throw (native)
[api]       at onRejected (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:77:24)
[api]       at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 
[api]   ilp-kit:spsp destroyed the sender object +4s
```

Please let me know if I miss something.

**Comment by sharafian** [comment]
Assuming that the connector's have each other's public keys, their instances of plugin virtual will internally know the right prefix (eg. `peer.correct.`). So when either connector gets an incoming message or payment, it will say it's from the ledger `peer.correct.`.

If the USD connector calls the trustline `peer.correct.` in its `env.list`, then all is good. That would explain why the USD side has no trouble quoting.

I think that maybe the MMK connector has been configured with the wrong trustline name, however. It will see an incoming payment from its trustline, which will have the ledger field `peer.correct.`. But if the MMK connector thinks the trustline is called `peer.incorrect.` So it thinks the trustline payment is coming from an unknown ledger, and fails.

How have you configured this trustline in your two `env.list`s? If their prefixes or currencies don't match, it would explain this issue.

(The structure of the `CONNECTOR_LEDGERS` field should be changed soon in order to make issues like this less likely to occur.)

**Comment by Winthan** [comment]
I stop modifying CONNECTOR_LEDGERS value and it works now.
